### ISSUE TITLE
Job sweps

### ISSUE THREAD

**Issue by GMG-Russell** [BinaryBandit/GunmetalRP#2]
All jobs should spawn with no weapons and no keypad crackers/lockpicks

Reason: So that they are not abused, helps the economy by having people buy stuff from dealers, makes them worth something instead of being this thing you magically spawn with, and will work well when we have the drop items on death (and maybe unconiousness)? 

Also it might seem harsh for cops since they dont get as much money than a thief, but I think we should allow them to use money printers they get from raids? idk i feel like they need money somehow. Either that or they spawn with weapons they cant drop.

**Comment by BinaryBandit** [comment]
Cops spawn with a pistol. Thieves no longer spawn with lockpicks or keypad crackers
